In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape #tells dimension of array

(5,)

In [7]:
arr = [[1,2,3,4],
      [5,6,7,8],
      [9,10,11,12]]

In [9]:
arr = np.array(arr)

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr.shape

(3, 4)

In [12]:
arr = arr.reshape(4,3)

In [13]:
arr.shape

(4, 3)

In [14]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
arr[:3,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [16]:
#create a numpy array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr = np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [19]:
arr = np.linspace(1,10,50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [21]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr[3:] = 25

In [23]:
arr

array([ 1,  2,  3, 25, 25, 25, 25, 25, 25, 25])

In [24]:
arr2 = arr #this is passing as refrence

In [25]:
arr2[7:] = 50

In [26]:
arr

array([ 1,  2,  3, 25, 25, 25, 25, 50, 50, 50])

In [27]:
#to remove this issue 
arr2 = arr.copy() #shallow copy

In [28]:
arr2[3:] = 764

In [29]:
arr2

array([  1,   2,   3, 764, 764, 764, 764, 764, 764, 764])

In [30]:
arr

array([ 1,  2,  3, 25, 25, 25, 25, 50, 50, 50])

In [31]:
arr2<50

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [33]:
arr[arr<50]

array([ 1,  2,  3, 25, 25, 25, 25])

In [32]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
np.ones(4)

array([1., 1., 1., 1.])

In [36]:
np.ones((3,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
#random distribution
np.random.rand(3,4)

array([[0.31813915, 0.01514235, 0.17270977, 0.06397198],
       [0.82622374, 0.62143484, 0.77774654, 0.68955808],
       [0.70124278, 0.88168888, 0.23710277, 0.43535013]])

In [39]:

arr_x = np.random.randn(4,4)
arr_x

array([[ 0.67058474, -0.80911002,  0.02780717,  1.51514462],
       [ 1.11340472, -0.00427347, -0.62490563,  0.09992622],
       [-0.09697867, -0.08426733,  0.43614384,  0.1041085 ],
       [ 0.06314038, -1.65999132,  1.1439591 , -0.71226358]])

In [40]:
np.random.randint(0,100,9).reshape(3,3)

array([[69, 73, 98],
       [46, 40, 74],
       [29, 37, 67]])

In [42]:
np.random.random_sample([1,8])

array([[0.73657943, 0.02526628, 0.30233062, 0.32263513, 0.89150074,
        0.09567963, 0.84169766, 0.76067452]])